In [2]:
print("Hello World")

Hello World


In [9]:
list = [i**2 for i in range(1,11)]
print(list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [10]:
!ls -lat

total 12812
drwxr-xr-x 1 SMENON 197121       0 May 12 17:11 Videos
drwxr-xr-x 1 SMENON 197121       0 May 12 15:30 .
-rw-r--r-- 1 SMENON 197121    1015 May 12 15:30 Python Exercises.ipynb
drwxr-xr-x 1 SMENON 197121       0 May 12 15:27 .ipynb_checkpoints
drwxr-xr-x 1 SMENON 197121       0 May 12 15:27 .ipython
drwxr-xr-x 1 SMENON 197121       0 May 12 15:23 Anaconda3
drwxr-xr-x 1 SMENON 197121       0 May 12 15:15 Downloads
drwxr-xr-x 1 SMENON 197121       0 May 12 00:01 .atom
drwxr-xr-x 1 SMENON 197121       0 May 11 23:57 .idlerc
-rw-r--r-- 1 SMENON 197121      67 May 11 23:40 .bash_history
-rw-r--r-- 1 SMENON 197121     123 May 10 13:00 .gitconfig
drwxr-xr-x 1 SMENON 197121       0 May  8 17:00 OneDrive
drwxr-xr-x 1 SMENON 197121       0 May  8 01:33 .p2
-rw-r--r-- 1 SMENON 197121    4759 May  7 17:23 .viminfo
drwxr-xr-x 1 SMENON 197121       0 May  7 10:41 .ssh
-rw-r--r-- 1 SMENON 197121 8388608 May  6 21:09 NTUSER.DAT
drwxr-xr-x 1 SMENON 197121       0 May  4 11:56 .VirtualBox
drw

In [11]:
x <- 3
y <- 4
z <- x*y
print(z)

NameError: name 'x' is not defined

In [15]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:3,])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
ar1 = np.random.randn(3,3)
print(ar1)
print(ar1.sum())
print(sum(ar1))
print(sum(ar1,axis=0))
print(sum(ar1,axis=1))

[[ 1.11895141 -0.5205213   1.45973178]
 [-0.4067114  -0.18040313 -0.34307698]
 [-0.43575267 -1.09598234  1.66242505]]
1.2586604350926733
[ 0.27648734 -1.79690676  2.77907985]


TypeError: sum() takes no keyword arguments

In [ ]:
from skiimage import data
photo = misc.imread()